// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sqmxkkgujfnycogvxdqw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNxbXhra2d1amZueWNvZ3Z4ZHF3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0MTQ1MjYsImV4cCI6MjA2NTk5MDUyNn0.h1vRxrHpiajMfnK9WhHzG3-B0Ci_J3zb_p5DWPBXT5A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});